version: 2.1

executors:
  rust:
    docker:
      - image: cimg/rust:1.89
    environment:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: "-D warnings"

jobs:
  test:
    executor: rust
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: cargo fetch
      - run:
          name: Build (debug) workspace
          command: cargo build --workspace
      - run:
          name: Run unit & doc tests (workspace)
          command: cargo test --workspace --all-targets
      - run:
          name: Run doc tests only
          command: cargo test --doc

  benches:
    executor: rust
    steps:
      - checkout
      - run:
          name: Ensure benchmarks compile
          command: cargo check --benches
      - run:
          name: Run benchmark suite (main branch only)
          command: cargo bench
      - run:
          name: Summarize benchmark reports
          command: |
            if [ -d target/criterion ]; then
              echo "=== Benchmark Report Paths ===" > benchmark-summary.txt
              find target/criterion -name index.html -printf "%P\n" >> benchmark-summary.txt || true
              cat benchmark-summary.txt
            fi
      - store_artifacts:
          path: target/criterion
          destination: criterion-reports
      - store_artifacts:
          path: benchmark-summary.txt
          destination: benchmark-summary

workflows:
  version: 2
  tests_all_branches:
    jobs:
      - test
  benches_main_only:
    jobs:
      - benches:
          filters:
            branches:
              only: main
